/**
 * Hand-maintained mirrors of `selfevals.api.schemas`.
 *
 * `types.gen.ts` (generated by `npm run gen:api` from the live OpenAPI
 * schema) is the source of truth for drift-checking — regenerate it and
 * diff when a backend schema changes. These hand types stay separate
 * because 30+ components already import named types from here and a
 * generated-types migration is a larger, separate change.
 */

export type WorkspaceSummary = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  owner_id: string | null;
  created_at: string;
  experiment_count: number;
  last_run_at: string | null;
};

export type WorkspaceDetail = WorkspaceSummary & {
  experiment_count: number;
  recent_health: number | null;
};

export type ExperimentSummary = {
  id: string;
  name: string;
  goal: string;
  mode: string;
  state: string;
  primary_metric: string;
  primary_target: { operator: string; value: number };
  proposer_strategy: string;
  max_iterations: number;
  created_at: string;
  updated_at: string;
  iteration_count: number;
};

export type IterationSummary = {
  id: string;
  iteration: number;
  state: string;
  hypothesis: string;
  proposed_parameters: Record<string, unknown>;
  primary_metric_name: string | null;
  primary_metric_value: number | null;
  delta_vs_best: number | null;
  decision_outcome: string | null;
  decision_rationale: string | null;
  cost_usd: number | null;
  duration_seconds: number | null;
  trace_run_ids: string[];
  created_at: string;
};

export type ExperimentDetail = {
  summary: ExperimentSummary;
  result: Record<string, unknown> | null;
  iterations: IterationSummary[];
};

export type ExperimentListPage = {
  items: ExperimentSummary[];
  total: number;
  limit: number;
  offset: number;
  has_more: boolean;
};

/** What the case declared it expected — only declared dimensions are present.
 * Mirror of `api.schemas.ExpectedView`. */
export type ExpectedView = {
  structured_output?: Record<string, unknown> | null;
  must_include?: string[] | null;
  must_not_include?: string[] | null;
  required_tools?: string[] | null;
  forbidden_tools?: string[] | null;
};

/** What the agent produced, projected to mirror `ExpectedView` for a direct
 * expected-vs-detected diff. Mirror of `api.schemas.DetectedView`. */
export type DetectedView = {
  content?: string | null;
  structured_output?: Record<string, unknown> | null;
  missing?: string[] | null;
  forbidden_present?: string[] | null;
  tools_invoked?: string[] | null;
};

/** One grader's verdict on a scenario, as it appears in
 * `ScenarioResult.grader_results[]`. `reason_pointer` is an `oss://` pointer to
 * the full reasoning when it was too large to inline; `breakdown` is the
 * grader's own nested detail (per-rule funnel, sub-scores). Kept loose on the
 * nested fields since their shape varies by grader type. */
export type GraderResult = {
  grader: string;
  label?: string | null;
  score?: number | null;
  reason?: string | null;
  reason_pointer?: string | null;
  confidence?: number | null;
  failure_modes?: string[] | null;
  breakdown?: Record<string, unknown> | null;
};

/** One evaluated scenario — a case, or one turn of a conversation case.
 * The single recursive shape behind `/results` and `/threads`. Mirror of
 * `api.schemas.ScenarioResult`. `expected`/`detected` are null when the case
 * declares nothing to compare; `matched`/`detected` are null with no trace. */
export type ScenarioResult = {
  case_id: string;
  case_name?: string | null;
  run_id?: string | null;
  trace_id?: string | null;
  iteration: number;
  position?: number | null;
  matched?: boolean | null;
  score?: number | null;
  label?: string | null;
  started_at?: string | null;
  message?: string | null;
  failure_modes: string[];
  expected?: ExpectedView | null;
  detected?: DetectedView | null;
  grader_results: GraderResult[];
  turns: ScenarioResult[];
};

export type ExperimentResults = {
  experiment_id: string;
  iteration: number | null;
  cases: ScenarioResult[];
  total: number;
};

export type FailureClusterExample = {
  run_id: string;
  experiment_id?: string | null;
};

/** One cluster = one failure mode (§J.6 v1). `status` is `"unknown"` for a mode
 * seen on a grade but not yet registered in the taxonomy. */
export type FailureClusterRow = {
  failure_mode: string;
  failure_mode_id?: string | null;
  title?: string | null;
  status: string;
  count: number;
  rate: number;
  examples: FailureClusterExample[];
};

export type FailureClusters = {
  workspace_id: string;
  window: { start: string | null; end: string | null };
  experiment_id: string | null;
  total: number;
  items: FailureClusterRow[];
};

export type DecisionRow = {
  id: string;
  iteration: number;
  outcome: string;
  automated_rationale: string;
  human_rationale: string | null;
  metrics_snapshot: Record<string, number>;
  created_at: string;
};

export type AnchorPoint = {
  experiment_id: string;
  experiment_name: string;
  iteration: number;
  primary_metric_name: string;
  primary_metric_value: number;
  decision_outcome: string;
  created_at: string;
};

export type SpanSummary = {
  id: string;
  parent_id: string | null;
  kind: string;
  name: string;
  started_at: string;
  duration_ms: number;
  detail: Record<string, unknown>;
};

export type TraceDetail = {
  id: string;
  run_id: string;
  experiment_id: string | null;
  experiment_name: string | null;
  iteration: number | null;
  thread_id: string | null;
  thread_position: number | null;
  final_state: string;
  started_at: string;
  ended_at: string | null;
  spans: SpanSummary[];
  metrics: Record<string, unknown>;
};

/** A conversation's turns, each a `ScenarioResult` — the same shape `/results`
 * uses (replaces the old flat `ThreadTurn`). Mirror of `api.schemas.ThreadResponse`. */
export type ThreadDetail = {
  thread_id: string;
  turn_count: number;
  turns: ScenarioResult[];
};

/**
 * One rolled-up funnel node (B2). Recursive: `children` is keyed by the
 * child node's `key`. Mirror of `selfevals.api.schemas.FunnelNodeResponse`.
 * The backend owns all the rollup math — the FE only renders this tree.
 */
export type FunnelNode = {
  key: string;
  count: number;
  mean_score: number | null;
  total_weight: number;
  label_counts: Record<string, number>;
  failure_mode_counts: Record<string, number>;
  children: Record<string, FunnelNode>;
};

export type FunnelDetail = {
  iteration_id: string;
  iteration: number;
  // Empty when no grader emitted a structured breakdown (the common case).
  nodes: Record<string, FunnelNode>;
};

// --- Compare (B3) -------------------------------------------------------
// Mirrors `selfevals.api.schemas.CompareResponse`. The server is the single
// source of truth for the diff math (the reporter's `compute_compare`); the
// FE renders this directly instead of recomputing deltas client-side.

export type CompareParamRow = {
  key: string;
  a: string;
  b: string;
  changed: boolean;
};

export type CompareMetricRow = {
  name: string;
  a: number | null;
  b: number | null;
  delta: number | null;
};

export type CompareFunnelRow = {
  path: string;
  a: number | null;
  b: number | null;
  delta: number | null;
};

export type CompareFailureModes = {
  only_a: Record<string, number>;
  only_b: Record<string, number>;
  common: Record<string, [number, number]>;
};

export type CompareRecommendation = {
  kind: 'winner' | 'tie' | 'different_metric' | 'none';
  winner: string | null;
  metric_name: string | null;
  a_metric_name: string | null;
  b_metric_name: string | null;
  a_value: number | null;
  b_value: number | null;
  delta: number | null;
  new_failure_modes: string[];
};

export type CompareResponse = {
  a_id: string;
  b_id: string;
  a_iteration: number;
  b_iteration: number;
  a_created_at: string;
  b_created_at: string;
  a_decision: string | null;
  b_decision: string | null;
  proposal_diff: CompareParamRow[];
  metrics_diff: CompareMetricRow[];
  failure_modes: CompareFailureModes;
  funnel_diff: CompareFunnelRow[];
  recommendation: CompareRecommendation;
  holdout_status: string;
};

// --- Metrics (observability layer) -------------------------------------
// Mirror of `selfevals.api.schemas.*MetricsResponse`. Every metrics endpoint
// shares the `{ workspace_id, window, experiment_id, total, items }` envelope;
// only the row shape differs. All take a `from`/`to` time-range (ISO strings).

export type MetricsWindow = { start: string | null; end: string | null };

type MetricsEnvelope<Row> = {
  workspace_id: string;
  window: MetricsWindow;
  experiment_id: string | null;
  total: number;
  items: Row[];
};

export type PassRateRow = { grader: string; label: string; count: number; rate: number };
export type FailureModeRow = { failure_mode: string; count: number; rate: number };
export type ToolRow = {
  tool_name: string;
  status: string;
  count: number;
  error_count: number;
  avg_duration_ms: number | null;
  retry_count: number;
};
export type CostRow = {
  provider: string;
  model: string;
  call_count: number;
  total_cost_usd: number;
  avg_cost_usd: number;
};
export type TokenRow = {
  provider: string;
  model: string;
  call_count: number;
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens: number;
  total_tokens: number;
};
export type LatencyRow = {
  metric: string;
  count: number;
  p50_ms: number | null;
  p95_ms: number | null;
  p99_ms: number | null;
};

export type PassRateMetrics = MetricsEnvelope<PassRateRow>;
export type FailureModeMetrics = MetricsEnvelope<FailureModeRow>;
export type ToolMetrics = MetricsEnvelope<ToolRow>;
export type CostMetrics = MetricsEnvelope<CostRow>;
export type TokenMetrics = MetricsEnvelope<TokenRow>;
export type LatencyMetrics = MetricsEnvelope<LatencyRow>;

// --- Datasets ----------------------------------------------------------

export type SplitAllocationView = {
  optimization: number;
  holdout: number;
  reliability: number;
  other: Record<string, number>;
};

export type DatasetStatisticsView = {
  total_cases: number;
  by_level: Record<string, number>;
  by_feature: Record<string, number>;
  by_source: Record<string, number>;
  by_risk: Record<string, number>;
  holdout_count: number;
  pii_breakdown: Record<string, number>;
};

export type DatasetSummary = {
  id: string;
  name: string;
  description: string | null;
  dataset_type: string;
  status: string;
  case_count: number;
  manifest_hash: string | null;
  created_at: string;
  updated_at: string;
};

export type DatasetListPage = {
  items: DatasetSummary[];
  total: number;
  limit: number;
  offset: number;
  has_more: boolean;
};

export type FeatureRef = { id: string; name: string } | Record<string, unknown>;

export type CaseSummary = {
  id: string;
  name: string;
  task_type: string;
  modalities: string[];
  input: Record<string, unknown>;
  graders: string[];
  holdout: boolean;
  is_conversation: boolean;
  feature: FeatureRef | null;
  level: string | null;
  dataset_type: string | null;
  latest_run_id: string | null;
  latest_trace_id: string | null;
};

export type DatasetDetail = {
  id: string;
  name: string;
  description: string | null;
  dataset_type: string;
  status: string;
  case_count: number;
  manifest_hash: string | null;
  split_allocation: SplitAllocationView;
  statistics: DatasetStatisticsView | null;
  cases: CaseSummary[];
  created_at: string;
  updated_at: string;
};

// --- Run / workspace mutation contracts --------------------------------

export type RunExperimentResponse = {
  experiment_id: string;
  workspace_id: string;
  state: string;
  run_id: string | null;
  job_id: string | null;
  dispatch: string;
};

export type RunExperimentRequest = {
  spec_path?: string;
  spec_inline?: Record<string, unknown>;
  dataset_id?: string;
  max_iterations?: number;
  reps?: number;
  persist_traces?: 'none' | 'all' | 'failed';
};

export type CreateWorkspaceRequest = {
  slug: string;
  name?: string;
  description?: string;
};

export type CreateDatasetRequest = {
  name: string;
  description?: string;
  dataset_type?: string;
  cases?: Record<string, unknown>[];
  cases_path?: string;
  split_allocation?: Record<string, number>;
};

export type PromoteCaseDraft = {
  case: Record<string, unknown>;
  source_trace_id: string;
  source_run_id: string;
  source_case_id: string;
  warnings: string[];
};

export type TraceAnnotation = {
  id: string;
  trace_id: string | null;
  case_id: string;
  annotator_id: string;
  verdict: 'good' | 'bad' | null;
  notes: string | null;
  confidence: number;
  flagged_for_adjudication: boolean;
  created_at: string;
};

export type TraceAnnotationList = {
  annotations: TraceAnnotation[];
};

export type SpanReplayResult = {
  provider: string;
  model: string;
  content: string;
  tokens_input: number;
  tokens_output: number;
  cost_usd: number | null;
  duration_ms: number;
  original_provider: string;
  original_model: string;
};

export type ProviderInfo = {
  provider: string;
  available: boolean;
  sdk_installed: boolean;
  has_key: boolean;
  models: string[];
};

export type ProvidersList = {
  providers: ProviderInfo[];
};

export type AppendDatasetCaseResult = {
  dataset: DatasetDetail;
  case_id: string;
  created_new_dataset: boolean;
};

// --- Failure-mode taxonomy (loop-closer 2A) ----------------------------

export type FailureMode = {
  id: string;
  slug: string;
  title: string;
  definition: string;
  status: string;
  parent_mode_id: string | null;
  proposed_by: string;
  example_count: number;
  first_seen_iteration: number | null;
  superseded_by: string | null;
  created_at: string;
  updated_at: string;
};

// --- Baseline & regression (loop-closer 2B) ----------------------------

export type Baseline = {
  dataset_id: string;
  iteration_id: string;
  experiment_id: string | null;
  primary_metric_name: string;
  primary_metric_value: number;
  error_rate: number | null;
  created_at: string;
};

export type RegressionFinding = {
  signal: string;
  baseline: number | null;
  current: number | null;
  delta: number | null;
  regressed: boolean;
  detail: string;
};

export type RegressionResult = {
  dataset_id: string;
  iteration_id: string;
  regressed: boolean;
  findings: RegressionFinding[];
};

// --- Error-analysis (loop-closer 2C) -----------------------------------
// Mirror of `analysis/schemas.py`. The bundle is the failed-traces + live
// taxonomy the human codes against; the result is what they compose back.

export type TaxonomyEntry = {
  id: string;
  slug: string;
  title: string;
  definition: string;
  status: string;
};

export type BundleGrade = {
  label: string;
  score: number | null;
  deterministic_modes: string[];
  judge_reason: string | null;
};

export type BundleMessage = { role: string; content: string };
export type BundleErrorSpan = { kind: string; name: string; error: string | null };

export type BundleTrace = {
  trace_id: string;
  run_id: string;
  thread_id: string | null;
  eval_case_id: string | null;
  grade: BundleGrade;
  transcript: BundleMessage[];
  first_error_span: BundleErrorSpan | null;
};

export type AnalysisBundle = {
  schema_version: string;
  workspace_id: string;
  experiment_id: string;
  iteration: number | null;
  taxonomy: TaxonomyEntry[];
  traces: BundleTrace[];
  instructions_ref: string;
};

// An assignment classifies a trace against an existing mode (`mode_id`) XOR
// proposes a new one (`new_mode_slug`). `proposed_modes` carries the new modes'
// definitions. This is what the annotation UI composes and POSTs.
export type AnalysisAssignment = {
  trace_id: string;
  mode_id?: string;
  new_mode_slug?: string;
  open_note?: string;
  quote?: string;
};

export type AnalysisProposedMode = {
  slug: string;
  title: string;
  definition: string;
  parent_slug?: string;
};

export type AnalysisResult = {
  assignments?: AnalysisAssignment[];
  proposed_modes?: AnalysisProposedMode[];
};

export type AnalysisIngestSummary = {
  assignments_applied: number;
  created_candidates: string[];
  updated_candidates: string[];
  hypotheses_recorded: number;
};

// --- Pairwise verdicts + tournaments -----------------------------------
// LLM + human pairwise judgments (RLHF / judge calibration) and N-candidate
// ranking via Elo / Bradley-Terry. Mirrors of `selfevals.api.schemas`.

/** One side of a compared pair. Mirror of `api.schemas.PairRefBody`. */
export type PairRef = {
  kind: string;
  trace_id?: string | null;
  case_id?: string | null;
  iteration_id?: string | null;
  content_snapshot?: string | null;
};

export type PairwiseVerdict = {
  id: string;
  a_ref: PairRef;
  b_ref: PairRef;
  preferred: 'a' | 'b' | 'tie';
  margin: number;
  rationale?: string | null;
  judge_kind: 'llm' | 'human';
  judge_id: string;
  rubric_version?: number | null;
  experiment_id?: string | null;
  case_id?: string | null;
  created_at: string;
};

/** A verdict to ingest. `id`/`workspace_id` are assigned server-side. */
export type IngestPairwiseVerdict = {
  a_ref: PairRef;
  b_ref: PairRef;
  preferred: 'a' | 'b' | 'tie';
  margin?: number;
  rationale?: string | null;
  judge_kind: 'llm' | 'human';
  judge_id: string;
  judge_model?: string | null;
  rubric_version?: number | null;
  position?: string | null;
  case_id?: string | null;
  dataset_id?: string | null;
};

export type PairwiseCalibrationCell = {
  rubric_version?: number | null;
  compared_pairs: number;
  agreements: number;
  disagreements: number;
  agreement_rate: number;
};

export type PairwiseCalibration = {
  compared_pairs: number;
  agreements: number;
  disagreements: number;
  agreement_rate: number;
  by_rubric_version: PairwiseCalibrationCell[];
};

export type TournamentCandidate = {
  id: string;
  output_text: string;
  trace_id?: string | null;
};

export type RunTournamentRequest = {
  candidates: TournamentCandidate[];
  /** Dotted path `mod:fn` to the LLM judge callable. */
  judge_entrypoint: string;
  rubric: string;
  strategy?: string;
  method?: string;
  baseline_id?: string | null;
  comparisons_per_candidate?: number;
  swiss_rounds?: number;
  swap_and_average?: boolean;
  case_input?: Record<string, unknown> | null;
};

export type RankingRow = {
  candidate_id: string;
  rank: number;
  score: number;
  wins: number;
  losses: number;
  ties: number;
  n_comparisons: number;
};

export type Tournament = {
  id: string;
  experiment_id?: string | null;
  strategy: string;
  method: string;
  candidate_ids: string[];
  baseline_id?: string | null;
  n_comparisons: number;
  swap_and_average: boolean;
  ranking: RankingRow[];
  created_at: string;
};

// --- Arena (code-variant bake-offs over git worktrees) --------------------
// Mirrors `selfevals.api.schemas` Arena* models + `arena.schemas.ArenaBundle`.

export type ArenaBudget = {
  max_rounds: number | null;
  max_variants: number | null;
  max_cost_usd: number | null;
};

export type ArenaSummary = {
  id: string;
  workspace_id: string;
  name: string;
  goal: string;
  repo_path: string;
  agent_command: string[];
  objective_metric: string;
  dataset_id: string | null;
  budget: ArenaBudget;
  current_round: number;
  state: string;
  winner_variant_id: string | null;
};

export type CreateArenaRequest = {
  name: string;
  goal: string;
  repo_path: string;
  agent_command: string[];
  spec_template: Record<string, unknown>;
  objective_metric: string;
  agent_env?: Record<string, string> | null;
  dataset_id?: string | null;
  budget?: Partial<ArenaBudget> | null;
};

export type ArenaVariant = {
  id: string;
  arena_id: string;
  name: string;
  git_ref: string;
  resolved_sha: string | null;
  worktree_path: string | null;
  hypothesis: string | null;
  created_in_round: number;
  state: string;
  error: string | null;
};

export type RegisterVariantRequest = {
  name: string;
  git_ref: string;
  setup_command?: string[] | null;
  env_overrides?: Record<string, string> | null;
  hypothesis?: string | null;
};

export type ArenaRoundEntry = {
  variant_id: string;
  experiment_id: string | null;
  run_job_id: string | null;
  status: string;
};

export type ArenaRound = {
  id: string;
  arena_id: string;
  index: number;
  entries: ArenaRoundEntry[];
  reps: number;
  state: string;
};

export type LaunchRoundRequest = {
  variant_ids?: string[] | null;
  reps?: number;
};

/** Cost preview for a round before launching it. `estimated_usd` is null when
 *  the agents are black-box (no declared per-token price); `basis` explains
 *  where the number came from. Mirror of `RoundCostEstimateResponse`. */
export type RoundCostEstimate = {
  estimated_usd: number | null;
  basis: string;
};

export type PromoteVariantResponse = {
  winner_variant_id: string;
  git_ref: string;
  resolved_sha: string | null;
  suggested_commands: string[];
};

export type GitRef = { name: string; sha: string };
export type GitRefsResponse = { repo_path: string; refs: GitRef[] };

export type ArenaBundleMetrics = {
  experiment_id: string;
  iteration_id: string;
  primary_metric: string;
  primary_value: number;
  guardrails: Record<string, number>;
  reliability: Record<string, number>;
  cost_usd: number | null;
  duration_seconds: number | null;
  error_rate: number;
  failure_mode_counts: Record<string, number>;
};

export type ArenaRoundHistoryPoint = {
  round: number;
  primary_value: number | null;
  cost_usd: number | null;
};

export type ArenaVariantCard = {
  variant_id: string;
  name: string;
  git_ref: string;
  resolved_sha: string | null;
  hypothesis: string | null;
  state: string;
  error: string | null;
  latest_result: ArenaBundleMetrics | null;
  history: ArenaRoundHistoryPoint[];
};

export type ArenaLeaderboardRow = {
  rank: number;
  variant_id: string;
  name: string;
  primary_value: number | null;
  delta_vs_best: number | null;
  cost_usd: number | null;
};

export type ArenaPairwiseVsBest = {
  variant_id: string;
  name: string;
  proposal_diff: { key: string; a: unknown; b: unknown; changed: boolean }[];
  metrics_diff: { name: string; a: number | null; b: number | null; delta: number | null }[];
  only_best: Record<string, number>;
  only_this: Record<string, number>;
  common_failure_modes: Record<string, [number, number]>;
  recommendation_kind: string;
  winner: string | null;
};

export type ArenaExemplarFailures = {
  variant_id: string;
  name: string;
  traces: {
    trace_id: string;
    grade_label: string;
    first_error_span: { kind: string; name: string; error: string | null } | null;
  }[];
};

export type ArenaConvergence = {
  converged: boolean;
  rounds_observed: number;
  min_delta: number;
  patience: number;
  best_value: number | null;
};

export type ArenaBundle = {
  arena: ArenaSummary & {
    budget_rounds_remaining: number | null;
    budget_variants_remaining: number | null;
  };
  round: number | null;
  variants: ArenaVariantCard[];
  leaderboard: ArenaLeaderboardRow[];
  pairwise_vs_best: ArenaPairwiseVsBest[];
  exemplar_failures: ArenaExemplarFailures[];
  convergence: ArenaConvergence;
  contract: {
    register_variant: string;
    launch_round: string;
    poll_round: string;
    promote: string;
  };
};
