"""Pydantic response models for the HTTP bridge.

These are *view* shapes — denormalized snapshots of the canonical
entities that the web UI needs. The canonical schemas in
`selfevals.schemas` stay the source of truth; this module simply
chooses what to expose and in what shape.

Split by resource under this package; re-exported here so existing
`from selfevals.api.schemas import X` imports keep working unchanged.
"""

from __future__ import annotations

from selfevals.api.schemas.datasets import (
    AnalysisIngestSummaryResponse,
    AppendDatasetCaseRequest,
    AppendDatasetCaseResponse,
    BaselineResponse,
    CreateDatasetRequest,
    DatasetDetailResponse,
    DatasetListPage,
    DatasetStatisticsView,
    DatasetSummary,
    EditFailureModeRequest,
    FailureModeListResponse,
    FailureModeResponse,
    MergeFailureModeRequest,
    RegressionCheckRequest,
    RegressionFindingResponse,
    RegressionResultResponse,
    SetBaselineRequest,
    SplitAllocationView,
)
from selfevals.api.schemas.experiments import (
    ActiveRun,
    ActiveRunsResponse,
    CompareFailureModes,
    CompareFunnelRow,
    CompareMetricRow,
    CompareParamRow,
    CompareRecommendation,
    CompareResponse,
    DecisionRecordResponse,
    ExperimentDetailResponse,
    ExperimentListPage,
    ExperimentSummary,
    FunnelNodeResponse,
    FunnelResponse,
    IterationListResponse,
    IterationSummary,
    RunExperimentRequest,
    RunExperimentResponse,
)
from selfevals.api.schemas.meta import (
    HealthResponse,
    SessionRequest,
    SessionResponse,
)
from selfevals.api.schemas.metrics import (
    CostMetricRow,
    CostMetricsResponse,
    FailureClusterExample,
    FailureClusterRow,
    FailureClustersResponse,
    FailureModeMetricRow,
    FailureModeMetricsResponse,
    LatencyMetricRow,
    LatencyMetricsResponse,
    MetricsWindow,
    PassRateMetricRow,
    PassRateMetricsResponse,
    TokenMetricRow,
    TokenMetricsResponse,
    ToolMetricRow,
    ToolMetricsResponse,
)
from selfevals.api.schemas.pairwise import (
    IngestPairwiseRequest,
    IngestPairwiseVerdict,
    PairRefBody,
    PairwiseCalibrationCellResponse,
    PairwiseCalibrationResponse,
    PairwiseIngestSummaryResponse,
    PairwiseVerdictResponse,
    RankingRowResponse,
    RunTournamentRequest,
    TournamentCandidateBody,
    TournamentResponse,
)
from selfevals.api.schemas.traces import (
    CaseListResponse,
    CaseSummary,
    DetectedView,
    ExpectedView,
    ExperimentResultsResponse,
    FeatureRef,
    PromoteCaseDraftRequest,
    PromoteCaseDraftResponse,
    ScenarioResult,
    SpanSummary,
    ThreadResponse,
    TraceResponse,
)
from selfevals.api.schemas.workspaces import (
    CreateWorkspaceRequest,
    WorkspaceListResponse,
    WorkspaceResponse,
    WorkspaceSummary,
)

__all__ = [
    "ActiveRun",
    "ActiveRunsResponse",
    "AnalysisIngestSummaryResponse",
    "AppendDatasetCaseRequest",
    "AppendDatasetCaseResponse",
    "BaselineResponse",
    "CaseListResponse",
    "CaseSummary",
    "CompareFailureModes",
    "CompareFunnelRow",
    "CompareMetricRow",
    "CompareParamRow",
    "CompareRecommendation",
    "CompareResponse",
    "CostMetricRow",
    "CostMetricsResponse",
    "CreateDatasetRequest",
    "CreateWorkspaceRequest",
    "DatasetDetailResponse",
    "DatasetListPage",
    "DatasetStatisticsView",
    "DatasetSummary",
    "DecisionRecordResponse",
    "DetectedView",
    "EditFailureModeRequest",
    "ExpectedView",
    "ExperimentDetailResponse",
    "ExperimentListPage",
    "ExperimentResultsResponse",
    "ExperimentSummary",
    "FailureClusterExample",
    "FailureClusterRow",
    "FailureClustersResponse",
    "FailureModeListResponse",
    "FailureModeMetricRow",
    "FailureModeMetricsResponse",
    "FailureModeResponse",
    "FeatureRef",
    "FunnelNodeResponse",
    "FunnelResponse",
    "HealthResponse",
    "IngestPairwiseRequest",
    "IngestPairwiseVerdict",
    "IterationListResponse",
    "IterationSummary",
    "LatencyMetricRow",
    "LatencyMetricsResponse",
    "MergeFailureModeRequest",
    "MetricsWindow",
    "PairRefBody",
    "PairwiseCalibrationCellResponse",
    "PairwiseCalibrationResponse",
    "PairwiseIngestSummaryResponse",
    "PairwiseVerdictResponse",
    "PassRateMetricRow",
    "PassRateMetricsResponse",
    "PromoteCaseDraftRequest",
    "PromoteCaseDraftResponse",
    "RankingRowResponse",
    "RegressionCheckRequest",
    "RegressionFindingResponse",
    "RegressionResultResponse",
    "RunExperimentRequest",
    "RunExperimentResponse",
    "RunTournamentRequest",
    "ScenarioResult",
    "SessionRequest",
    "SessionResponse",
    "SetBaselineRequest",
    "SpanSummary",
    "SplitAllocationView",
    "ThreadResponse",
    "TokenMetricRow",
    "TokenMetricsResponse",
    "ToolMetricRow",
    "ToolMetricsResponse",
    "TournamentCandidateBody",
    "TournamentResponse",
    "TraceResponse",
    "WorkspaceListResponse",
    "WorkspaceResponse",
    "WorkspaceSummary",
]
